### ISSUE TITLE
Create a coherent organizational structure for site

### ISSUE THREAD

**Issue by danerwilliams** [fisher-hall/website#11]
i.e. add content, pages, resources folders so that not everything is in the root directory

**Comment by antithalian** [comment]
Moving things around under the structure that user-visible pages belong in a "pages" directory, CSS/JS belong in a "resources" dir, and photos and other stuff belong in a "content" dir.

**Comment by antithalian** [comment]
Reopening on the basis that I broke this last time and still hasn't been done.
