### ISSUE TITLE
Add 2020 Welcome weekend

### ISSUE THREAD

**Issue by danerwilliams** [fisher-hall/website#3]
Change welcome weekend page for fall 2020

**Comment by antithalian** [comment]
Have we heard *anything* from the Welcome Weekend guys about what, if anything, they want put up? 

If not, do we want to throw up some placeholder stuff? We can reuse MJ and LaCroix's profile cards from last year when they were ambassadors...

**Comment by antithalian** [comment]
Added by removing everything except captains from this year and the 2019 video and other info we had...
